### ISSUE TITLE
Add missing CA cert paths from golang source

### ISSUE THREAD

**Issue by hellais** [measurement-kit/go-measurement-kit#19]
See: https://golang.org/src/crypto/x509/root_linux.go. I think two of these paths are missing from our own lookup function.

**Comment by bassosimone** [comment]
Thanks for the reminder! I'm going to close this issue with the following motivation:

1. the code in this repository has been superseded by https://github.com/ooni/probe-engine

2. the ooni/probe-engine code will use Go native HTTPS client for performing several operations including downloading the assets

3. if the CA is not found by Go _during that operation_, that's a Go bug that we should report to Go to have it fixed (and Go works on many Linux distros, so I believe what they do is fine, and better than what we were doing here, as highlighted by your link showing that we were doing less than them)

4. in such case, the probe-engine (and hence probe-cli) will have the possibility of specifying manually a CA bundle to use, therefore, Linux users could always save themlselves

5. the assets include the curl CA, which will be stored in the `~/.ooni/assets` home directory and hence we will always have a valid CA for cURL and MK.
