### ISSUE TITLE
NetTest / NetTestOptions doesn't support test-specific input

### ISSUE THREAD

**Issue by willscott** [measurement-kit/go-measurement-kit#2]
per the `Nettest` and `NetTestOptions` structs in
https://github.com/measurement-kit/go-measurement-kit/blob/master/measurement_kit.go

There doesn't appear to be an obvious way to support test-specific configuration, which is primarily needed for passing the input of desired domains to the web_connectivity test.

Should we just add an `Input` key to `NetTestOptions`, or is it worth factoring out an interface that can be defined in a test-specific way?

**Comment by bassosimone** [comment]
> Should we just add an Input key to NetTestOptions, or is it worth factoring out an interface that can be defined in a test-specific way?

Having more test specific ways of filling the `inputs` list in the JSON is probably nice.

**Comment by hellais** [comment]
This is implemented in: https://github.com/measurement-kit/go-measurement-kit/commit/1d68732fe73957e774e3ffb316dd30103ffadb07.

See the web_connectivity example for usage.
